/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'
import { ValidationError } from 'ajv'

export interface AbObj {
    a: string
    b: string
}

export const AbObj = {
    validate: (await import('./schemas/ab-obj.schema.js')).validate as ValidateFunction<AbObj>,
    get schema() {
        return AbObj.validate.schema
    },
    get errors() {
        return AbObj.validate.errors ?? undefined
    },
    is: (o: unknown): o is AbObj => AbObj.validate(o) === true,
    assert: (o: unknown) => {
        if (!AbObj.validate(o)) {
            throw new ValidationError(AbObj.errors ?? [])
        }
    },
} as const
